name: "Analyze-repo"

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    permissions:
  # required for all workflows
      security-events: write

    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository hello-world
      uses: actions/checkout@v2
      with:
        repository: sodji98/hello-world

    
    - name: Compile
      run: |
        cp ../../pvs/* .
        chmod 777 script.sh
        ./script.sh
        cp *.sarif ../../pvs
        
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Run
      run: cp ../../pvs/*.sarif .
   
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artefatti
        path: results.sarif
      
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: results.sarif
